#!/usr/bin/env php
<?php

use CodeIgniter\Boot;

define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

require __DIR__ . '/vendor/autoload.php';

require __DIR__ . '/app/Config/Paths.php';
$paths = new Config\Paths();

Boot::bootSpark($paths);
